#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/redis-server
# DAEMON_ARGS=/etc/redis/landlord.conf
# NAME=redis-landlord
# DESC=redis-landlord

RUNDIR=/var/run/redis
# PIDFILE=$RUNDIR/redis-landlord.pid

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
        . /etc/default/$NAME
fi

set -e

run() {
	case "$1" in
	  start)
		echo -n "Starting $DESC: "
		mkdir -p $RUNDIR
		touch $PIDFILE
		chown redis:redis $RUNDIR $PIDFILE
		chmod 775 $RUNDIR $PIDFILE

		if [ -n "$ULIMIT" ]
		then
			ulimit -n $ULIMIT
		fi

		if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
		then
			echo "$NAME."
		else
			echo "failed"
		fi
		;;
	  stop)
		echo -n "Stopping $DESC: "
		if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
		then
			echo "$NAME."
		else
			echo "failed"
		fi
		rm -f $PIDFILE
		sleep 1
		;;

	  restart|force-reload)
		${0} stop
		${0} start
		;;

	  status)
		echo -n "$DESC is "
		if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
		then
			echo "running"
		else
			echo "not running"
			exit 1
		fi
		;;

	  *)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
		exit 1
		;;
	esac

	exit 0
}
