#! /bin/sh
### BEGIN INIT INFO
# Provides:             redis-landlord
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    redis-server - Persistent key-value db
# Description:          redis-server - Persistent key-value db
### END INIT INFO

. <initd>/redis-server-base

DAEMON_ARGS=<confdir>/landlord.conf
NAME=redis-landlord
DESC=redis-landlord
PIDFILE=$RUNDIR/<pidfile>

run $1
